# Generated by Django 5.0.6 on 2024-07-09 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=32, unique=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='director_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ozvuchka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('age', models.PositiveIntegerField(default=0)),
                ('date_registered', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=100, unique=True)),
                ('anime_name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('anime_name_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
                ('image', models.ImageField(upload_to='anime_img/')),
                ('popular', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('announcement', 'Аnnouncement'), ('came out', 'Сame out')], default='came out', max_length=32)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('studio', models.CharField(max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jutsu.category')),
                ('director', models.ManyToManyField(to='jutsu.director')),
                ('genre', models.ManyToManyField(to='jutsu.genre')),
                ('ozvuchka', models.ManyToManyField(to='jutsu.ozvuchka')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jutsu.type')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate the item with 0 to 6 stars.', verbose_name='Rating')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jutsu.anime')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jutsu.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('anime_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jutsu.anime')),
                ('parent_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='jutsu.rating')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jutsu.userprofile')),
            ],
        ),
    ]
